spring:
  application:
    name: SCW-WEB
  
  # thymeleaf 配置
  thymeleaf: 
    prefix: classpath:/templates/
    suffix: .html
    cache: false #开发的时候禁用缓存
  
  # spring session 设置
  session: 
    # spring session 使用 redis
    store-type: redis
    # spring session 过期时间
    timeout: 1800
  
  # 配置 Redis
  redis:  
    host: 127.0.0.1
    port: 6379

    # redis 连接数设置 
    jedis: 
      pool: 
         max-idle: 100 

  
eureka: 
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: SCW-WEB
    prefer-ip-address: true
    
server: 
  port: 7005
  
feign:
  hystrix:
    enabled: true

     